# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
# formula = weight / (height**2) * 730

import numpy as np
weights = np.array([110, 120, 130, 140, 150, 160, 170])  # in kilograms
heights = np.array([69, 70, 71, 72, 73, 74, 75])  # in meters

# Calculate BMI using the formula: BMI = weight / (height**2) * 730
bmi_values = weights / (heights**2) * 730

# Print the BMI values
print("BMI values:", bmi_values)





BMI values: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [2]:
import numpy as np

def create_random_matrix(rows, columns, shape='random', dtype=float):
    """
    Create a random matrix based on the given parameters.

    Parameters:
    - rows: Number of rows in the matrix.
    - columns: Number of columns in the matrix.
    - shape: (Optional) Shape of the matrix. Default is 'random'. Other options include 'zeros' and 'ones'.
    - dtype: (Optional) Data type of the matrix. Default is float.

    Returns:
    - A NumPy array representing the random matrix.
    """

    if shape == 'random':
        matrix = np.random.rand(rows, columns)
    elif shape == 'zeros':
        matrix = np.zeros((rows, columns), dtype=dtype)
    elif shape == 'ones':
        matrix = np.ones((rows, columns), dtype=dtype)
    else:
        raise ValueError("Invalid shape. Supported shapes are 'random', 'zeros', and 'ones'.")

    return matrix.astype(dtype)

# Example usage:
rows = 4
columns = 5 
random_matrix = create_random_matrix(rows, columns)
print("Random Matrix:")
print(random_matrix)

zeros_matrix = create_random_matrix(rows, columns, shape='zeros', dtype=int)
print("\nZeros Matrix:")
print(zeros_matrix)

ones_matrix = create_random_matrix(rows, columns, shape='ones', dtype=float)
print("\nOnes Matrix:")
print(ones_matrix)



Random Matrix:
[[0.31007287 0.20096594 0.62340006 0.71653862 0.49082596]
 [0.16149434 0.86241927 0.78274537 0.03388216 0.21091784]
 [0.52432675 0.97477858 0.11790438 0.09449576 0.80781008]
 [0.66562406 0.89267229 0.79606521 0.89651225 0.70709228]]

Zeros Matrix:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Ones Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [43]:
!pip install pandas
import pandas as pd

# File paths
file_path_2017 = r'C:\Users\Kunle Kuforiji\Desktop\Boston Red Sox hitting data 2017.csv'
file_path_2018 = r'C:\Users\Kunle Kuforiji\Desktop\Boston Red 2018.csv'

# Load data into DataFrames
data_2017 = pd.read_csv(file_path_2017)
data_2018 = pd.read_csv(file_path_2018)

# Display the loaded data (optional)
print("Data for 2017:")
print(data_2017.head())

print("\nData for 2018:")
print(data_2018.head())

# Read CSV files into pandas DataFrames
df_2017 = pd.read_csv(file_path_2017)
df_2018 = pd.read_csv(file_path_2018)

# Extract the SLG column from each DataFrame
slg_2017 = df_2017['SLG']
slg_2018 = df_2018['SLG']

# Convert SLG columns to NumPy arrays
slg_array_2017 = np.array(slg_2017)
slg_array_2018 = np.array(slg_2018)

# Perform differential operation
slg_difference = slg_array_2018 - slg_array_2017

# Display the results
print("SLG Difference:")
print(slg_difference)





Data for 2017:
   Rk Pos               Name  Age    G   PA   AB   R    H  2B  ...    OBP  \
0   1   C  Christian Vazquez   26   99  345  324  43   94  18  ...  0.330   
1   2  1B     Mitch Moreland   31  149  576  508  73  125  34  ...  0.326   
2   3  2B     Dustin Pedroia   33  105  463  406  46  119  19  ...  0.369   
3   4  SS    Xander Bogaerts   24  148  635  571  94  156  32  ...  0.343   
4   5  3B      Rafael Devers   20   58  240  222  34   63  14  ...  0.338   

     SLG    OPS  OPS+   TB  GDP  HBP  SH  SF  IBB  
0  0.404  0.735    91  131   14    3   0   1    0  
1  0.443  0.769    99  225   14    6   0   5    6  
2  0.392  0.760   100  159   11    2   2   4    4  
3  0.403  0.746    95  230   17    6   0   2    6  
4  0.482  0.819   111  107    5    0   0   0    3  

[5 rows x 28 columns]

Data for 2018:
   Rk Pos               Name  Age    G   PA   AB   R    H  2B  ...    OBP  \
0   1   C  Christian Vazquez   26   99  345  324  43   94  18  ...  0.330   
1   2  1B     Mit

In [45]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

import numpy as np

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS',
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
             ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
             ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
             ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# Use this function to actually open the data inside of a NumPy structured array
def open_data(file_path):
    data = np.genfromtxt(file_path, delimiter=',', skip_header=1, names=FIELDS, dtype=DATATYPES)
    return data

# Example usage:
file_path = r'C:\Users\Kunle Kuforiji\Desktop\Boston Red Sox hitting data 2017.csv'  
your_data = open_data(file_path)
print(your_data)


[( 1, b'C', b'Christian Vazquez', 26,  99, 345, 324,  43,  94, 18, 2,  5,  32,  7, 2, 17,  64, 0.29 , 0.33 , 0.404, 0.735,  91, 131, 14, 3, 0, 1, 0)
 ( 2, b'1B', b'Mitch Moreland', 31, 149, 576, 508,  73, 125, 34, 0, 22,  79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14, 6, 0, 5, 6)
 ( 3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406,  46, 119, 19, 0,  7,  62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11, 2, 2, 4, 4)
 ( 4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571,  94, 156, 32, 6, 10,  62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17, 6, 0, 2, 6)
 ( 5, b'3B', b'Rafael Devers', 20,  58, 240, 222,  34,  63, 14, 0, 10,  30,  3, 1, 18,  57, 0.284, 0.338, 0.482, 0.819, 111, 107,  5, 0, 0, 0, 3)
 ( 6, b'LF', b'Andrew Benintendi', 22, 151, 658, 573,  84, 155, 26, 1, 20,  90, 20, 5, 70, 112, 0.271, 0.352, 0.424, 0.776, 102, 243, 16, 6, 1, 8, 7)
 ( 7, b'CF', b'Jackie Bradley Jr.', 27, 133, 541, 482,  58, 118, 19, 3, 17,  63,  8, 3, 48, 124, 0.245, 0.323, 0.